/**
 * Motion Canvas utilities for embedded animations.
 *
 * Note: Runtime initialization is provided by the virtual module
 * `virtual:motion-canvas-runtime` which is generated by the Vite plugin.
 */

// Color utilities
export { getColors, getStaticColors, defaultColors } from "./colors";
export type { ColorName, ColorPalette } from "./colors";

// Presenter class
export { MotionCanvasPresenter } from "./presenter";
export type { PresenterCallbacks, PresenterSettings } from "./presenter";
