name: Build Documentation
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install animations dependencies
        run: bun install
        working-directory: animations

      - name: Build animations
        run: bun run build
        working-directory: animations

      - name: Install root dependencies
        run: bun install

      - name: Build notes
        run: bun run build
        env:
          BASE_URL: ${{ github.event.repository.name }}

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
      - id: deployment
        uses: actions/deploy-pages@v4
